apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: rhacm-installed-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: rhacm-installed-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: geo-hub-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - rhacm-installed
policies:
  - name: rhacm-installed
    manifests:
      - path: manifests
        patches:
          - apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                operators.coreos.com/advanced-cluster-management.open-cluster-management: ''
              name: advanced-cluster-management
              namespace: open-cluster-management
            spec:
              config:
                nodeSelector:
                  node-role.kubernetes.io/infra: ""
                tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Exists
                - effect: NoExecute
                  key: node-role.kubernetes.io/infra
                  operator: Exists
