---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: Basic
  enableClusterBackup: false
  disableUpdateClusterImageSets: true
  #disableHubSelfManagement: true
  ingress:
    sslCiphers:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
  separateCertificateManagement: false
  #imagePullSecret: pull-secret
  #customCAConfigmap: cluster-root-ca-bundle
  overrides:
    components:
      - enabled: true
        name: multiclusterhub-repo
      - enabled: true
        name: search
      - enabled: true
        name: management-ingress
      - enabled: true
        name: console
      - enabled: true
        name: insights
      - enabled: true
        name: grc
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: volsync
      - enabled: true
        name: multicluster-engine
      - enabled: false
        name: cluster-proxy-addon
      - enabled: false
        name: cluster-backup
# https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/install/installing#installing-on-infra-node
#  tolerations:
#    - effect: NoSchedule
#      key: node-role.kubernetes.io/infra
#      operator: Exists
#    - effect: NoExecute
#      key: node-role.kubernetes.io/infra
#      operator: Exists
#  nodeSelector:
#    node-role.kubernetes.io/infra: ""