apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: app-infinite-mario
  namespace: rhacm-applications
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-infinite-mario
# ---
# apiVersion: apps.open-cluster-management.io/v1
# kind: Channel
# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#     apps.open-cluster-management.io/reconcile-rate: medium
#   name: ggithubcom-kenmoini-multiverse-of-multicluster-madness
#   namespace: rhacm-channels
# spec:
#   type: Git
#   pathname: 'https://github.com/kenmoini/multiverse-of-multicluster-madness'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/infinite-mario
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: app-infinite-mario
  name: app-infinite-mario
  namespace: rhacm-applications
spec:
  channel: rhacm-channels/ggithubcom-kenmoini-multiverse-of-multicluster-madness
  placement:
    placementRef:
      kind: PlacementRule
      name: all-openshift-clusters
