---
# This ArgoCD Application is used to load in all the other ArgoCD Applications that are used to manage the Hub of Hubs cluster
# It will sync down the gitops-apps directory and all sub-directories, which are atomic Applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-of-hubs-cluster-apps
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/kenmoini/multiverse-of-multicluster-madness'
    targetRevision: HEAD
    path: hub-of-hubs/gitops-apps
    #directory:
    #  recurse: true
    kustomize:
      version: v4.4.1
  project: hub-of-hubs-cluster-apps
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false # overrides changes made on the cluster that drift from git state