apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: app-omg-shoes-pg
  #annotations:
  #  argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: app-omg-shoes-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: management-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  #policySets:
  #  - app-omg-shoes
policies:
  - name: app-omg-shoes
    manifests:
      - path: manifests