apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: install-reflector-chart-policygenerator
  namespace: rhacm-applications
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - install-reflector-chart-policygenerator
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm/policy-generators/install-reflector-chart
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: install-reflector-chart-policygenerator
  name: install-reflector-chart-policygenerator
  namespace: rhacm-applications
spec:
  channel: rhacm-channels/ggithubcom-kenmoini-multiverse-of-multicluster-madness
  placement:
    placementRef:
      kind: PlacementRule
      name: management-clusters
