apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: placement-inheritance-pg
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: placement-inheritance-pg-pb
policyDefaults:
  namespace: rhacm-policies
  # Use the name of an existing placement rule
  placement:
    placementRuleName: management-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  policySets: 
    - placement-inheritance
policies:
  - name: placement-rules
    manifests:
      - path: placementrules
