kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: hoh-vault
spec:
  #controller: dev
  provider:
    vault:
      auth:
        # create this secret with:
        # oc create secret generic vault-token-auth --from-literal=token=root -n vault
        tokenSecretRef:
          key: token
          name: vault-token-auth
          namespace: vault
      path: kv
      server: 'http://vault.vault.svc.cluster.local:8200'
      version: v2
